### ISSUE TITLE
Create account not working

### ISSUE THREAD

**Issue by raaitken** [raaitken/GameRankings#44]
Trying to create an account but getting an error message "Form submission canceled because the form is not connected"

**Comment by raaitken** [comment]
![Screenshot 2023-07-02 110549](https://github.com/raaitken/GameRankings/assets/18446932/cbdd522e-1840-44f7-af33-222ba9c4e357)

**Comment by EuanCrawford** [comment]
fixed, just needs to be /api/users rather than /users in the fetch request
